### ISSUE TITLE
cannot run HPVCreator on OSX 10.11

### ISSUE THREAD

**Issue by themancalledjakob** [HasseltVR/Holo_Toolset#1]
When trying to run the binary, I get this error:

`dyld: Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
Referenced from: /Users/USER/Downloads/HPVCreator.app/Contents/MacOS/HPVCreator
Reason: image not found`

Do I have to install the qt framework from here http://code.qt.io/cgit/qt/qtbase.git/?

**Comment by HasseltVR** [comment]
Hello @themancalledjakob , 

There were some Frameworks not included in the app bundle. Should be fixed now, I've updated the binary packages/ZIPS attached to the release.

**Comment by HasseltVR** [comment]
Enough succesful reports to declare this fixed.
