### ISSUE TITLE
Cannot run HPVCreator in Windows 8.1

### ISSUE THREAD

**Issue by themancalledjakob** [HasseltVR/Holo_Toolset#2]
```
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix the problem"

```
I tried running the HPVCreator.exe file.
Qt5Core.dll, Qt5Gui.dll & Qt5Widgets.dll are next to it in the same folder.

**Comment by Echolaitoc** [comment]
same in Windows 10

**Comment by HasseltVR** [comment]
Hello @themancalledjakob , 

There were some Qt specific plugins/libraries not included in the deployment version. Should be fixed now, I've updated the binary packages/ZIPS attached to the release.

**Comment by HasseltVR** [comment]
Enough succesful reports to declare this fixed.
